openapi: 3.0.0
info:
  title: Labyrinth Game API
  description: API für ein 5x5 Labyrinth-Spiel, in dem der Spieler von A1 nach E5 navigiert.
  version: 1.2.0

paths:
  /game/start:
    post:
      summary: Starte ein neues Spiel
      operationId: startGame
      responses:
        '200':
          description: Spiel erfolgreich gestartet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'

  /game/move:
    post:
      summary: Bewege den Spieler in eine Richtung
      operationId: movePlayer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoveRequest'
      responses:
        '200':
          description: Neuer Zustand nach der Bewegung
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'
        '400':
          description: Ungültige Bewegung oder Regelverstoß
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /game/status:
    get:
      summary: Status des aktuellen Spiels abrufen
      operationId: getGameStatus
      responses:
        '200':
          description: Der aktuelle Spielstatus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'

components:
  schemas:
    GameState:
      type: object
      properties:
        position:
          type: string
          example: "A1"
        status:
          type: string
          enum: [ongoing, success, failed]
          example: "ongoing"
        message:
          type: string
          example: "Du hast dich erfolgreich bewegt."
        grid:
          type: array
          description: 5x5 Spielfeld mit blockierten Feldern (X)
          items:
            type: array
            items:
              type: string
          example: 
            - ["A1", "X",  "A3", "A4", "A5"]
            - ["B1", "B2", "B3", "X", "B5"]
            - ["C1", "X", "C3", "C4", "C5"]
            - ["D1", "D2", "X", "D4", "D5"]
            - ["E1", "E2", "E3", "E4", "E5"]

    MoveRequest:
      type: object
      properties:
        direction:
          type: string
          enum: [left, right, up, down]
          example: "right"

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Ungültige Bewegung - Blockiertes Feld oder Spielfeldrand!"
        message:
          type: string
          example: "Du kannst dich nicht nach links bewegen, da sich dort eine Wand befindet."
